Repository MentorMate/rn-bootstrap, pull requests merged in 2023-11, with the labels that each got.

#19 chore: update readme
  README.md
  package.json
Labels: documentation

#21 feat: add release please
  .github/workflows/ci.yml
Labels: enhancement

#23 chore: update workflow logic
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: enhancement

#20 feat/storybook
  README.md
  baseProject/App.storybook.tsx
  baseProject/config/storybook/main.js
  baseProject/config/storybook/preview.js
  baseProject/index.js
  baseProject/metro.config.js
  src/commands/start-project.ts
  src/tools/constants.ts
  src/tools/dependency-versions.ts
  src/tools/option-utils.ts
  src/tools/options.ts
  src/types/BaseProjectTemplateParams.ts
  src/types/StartProjectOptionSelectionResult.ts
Labels: enhancement

#31 chore: swap to npm-publish action
  .github/workflows/release.yml
Labels: enhancement

#34 Add community guideline files
  .github/code_of_conduct.md
  .github/pull_request_template.md
Labels: documentation

#37 chore: bump baseproject deps & rn version
  baseProject/package.json
  src/tools/dependency-versions.ts
Labels: enhancement

#39 chore: add keywords for npm registry
  package.json
Labels: documentation

#42 fix: storybook init process
  baseProject/config/storybook/main.ts
  baseProject/config/storybook/preview.js
  baseProject/config/storybook/preview.tsx
  src/commands/start-project.ts
  src/extensions/replace-file.ts
  src/types/RnBootstrapToolbox.ts
Labels: bug
